from django.urls import path, re_path as url
# from hork.api.Project_API import *
from .views import *

app_name = 'hork'
urlpatterns = [
    url(r'^$', login, name="login"),
    path('index/', index),
    path('logout/', logout),
    path('pro/', dopro_info, name="pro"),
    path('cre_project/', cre_project),
    path('del_project/', del_project),
    path('upd_project/', update_project),
    path('usr/', dousr_info, name="usr"),
    path('cre_user/', cre_user),
    path('register/', register),
    path('del_user/', del_user),
    path('upd_user/', update_user),
    path('update_pwd/', update_pwd),
    path('update_user_pwd/', update_user_pwd),
    path('setu/', setu),
    path('con/', get_swift_counters, name="con"),
    path('cre_con/', cre_conter),
    path('del_con/', del_conter),
    path('con/<str:count_name>', get_objects),
    path('cre_folder/', cre_folder),
    path('upload/', upload),
    # path('download/', download),
    # path('fol/<container_name>/<path:folder_name>', get_folder_objects),
    path('del_obj/', del_obj),
    path('download/<down_object>', download),
    path('image/', image, name='image'),
    path('txt/', txt, name='txt'),
    path('music/', music, name='music'),
    path('video/', video, name='video'),
    path('untype/', untype, name='untype'),
    path('get_cred/', get_cred),
    path('cre_cred/', cre_cred),
    path('get_options/', get_options),
    path('set_session/', set_session),
    path('put_admin_role/', put_admin_role),
    path('put_user_role/', put_user_role),
    path('del_admin_role/', del_admin_role),
    path('del_user_role/', del_user_role),
    path('del_pro_user/', del_pro_user),
    path('get_role/', get_role),
    path('prouseredit/', prouseredit),
    path('alluser/', alluser),
    path('prouser/', prouser),
    path('get_data/', get_data),
    path('selecthtml/', selecthtml),
    # path('getData/', getData),
    # path('setSession/', setSession),
    # path('select1/', select1),
    # path('get_data1/', get_data1),
    # path('set_selected_id/', set_selected_id),
]